source :rubygems

gem 'rake'
gem 'unicorn', '~> 3.3.1'
gem 'activesupport', '~> 3.0.0'
gem 'sinatra', '~> 1.2.0'
gem 'haml', '~> 3.0.0'
gem 'mongoid', '~> 2.0.0'
gem 'jammit', '~> 0.5.4'
gem 'rack-flash', '~> 0.1.1'
gem 'rackamole'
gem 'nokogiri'
gem 'amqp', '~> 0.7.1'
gem 'bunny'
gem 'god'

group :development, :test do
  gem 'sinatra-reloader'
  gem 'rspec', '>= 2.2.0'
  gem 'mongoid-rspec', '>= 1.3.2'
  gem 'machinist_mongo', '>= 1.1.1'
  gem 'forgery', '>= 0.3.6'
  gem 'capybara', '>= 1.0.0.beta1'
  gem 'akephalos', :git => 'git://github.com/dam5s/akephalos.git'
  gem 'autotest'
  gem 'ruby-debug19'
  gem 'awesome_print', :require => 'ap'
  gem 'shotgun'
  gem 'racksh'
  gem 'capistrano'
end
