source :rubygems

gem 'rake'
gem 'unicorn'
gem 'activesupport'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'mongoid'
gem 'bson_ext'
gem 'jammit'
gem 'nokogiri'
gem 'amqp'
gem 'bunny'
gem 'mime'

group :development, :test do
  gem 'sinatra-reloader'
  gem 'rspec', '>= 2.2.0'
  gem 'mongoid-rspec', '>= 1.3.2'
  gem 'machinist_mongo', '>= 1.1.1'
  gem 'database_cleaner'
  gem 'forgery', '>= 0.3.6'
  gem 'capybara', '>= 1.0.0.beta1'
  gem 'selenium-client'
  gem 'autotest'
  gem 'debugger'
  gem 'awesome_print', :require => 'ap'
  gem 'shotgun'
  gem 'racksh'
  gem 'capistrano'
end
