:topic: jobs
:consumers:
  - :name: High Priority Jobs
    :key: jobs.high
  - :name: Medium Priority Jobs
    :key: jobs.medium

:server:
  :user: guest
  :password: guest
  :host: localhost
  :logging: true
