gzip_assets: off
package_path: jam

javascripts:
  head:
    - public/js/head.js
  aggregator:
    - public/js/jquery-1.8.1.js
    - public/js/aggregator.js
  manager:
    - public/js/jquery-1.8.1.js
    - public/js/chosen.jquery.js
    - public/js/manager.js

stylesheets:
  aggregator:
    - public/css/reset.css
    - public/css/base.css
    - public/css/application.css
    - public/css/aggregator.css
    - public/css/article.css
    - public/css/user.css
  manager:
    - public/css/reset.css
    - public/css/base.css
    - public/css/chosen.css
    - public/css/application.css
    - public/css/manager.css
    - public/css/pictos.css
    - public/css/article.css
