defaults: &defaults
  host: localhost
  #slaves:
    #- host: slave1.local
      #port: 27018
    #- host: slave2.local
      #port: 27019
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: somanyfeeds_development

test:
  <<: *defaults
  database: somanyfeeds_test

# Heroku Mongo HQ plugin configuration
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
