default: &defaults
  options:
    allow_dynamic_fields: true
    include_root_in_json: false
    raise_not_found_error: true

development:
  <<: *defaults
  sessions:
    default:
      database: somanyfeeds_dev
      username: somanyfeeds_db
      password: yS2$zkL6LC!q
      hosts:
        - ds035428.mongolab.com:35428

test:
  <<: *defaults
  sessions:
    default:
      database: somanyfeeds_test
      hosts:
        - localhost:27017

production:
  <<: *defaults
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
